retrieveUnpackaged/objects/Delivery__c.object
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <label>Delivery Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Material__c.object
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Model Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>Delivery__c</fullName>
        <description>/</description>
        <label>Delivery Number</label>
        <referenceTo>Delivery__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ItemType__c</fullName>
        <description>/ in, out or cons.</description>
        <label>Item Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <description>/</description>
        <label>Model Number</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderQuantity__c</fullName>
        <description>VBAP-KWMENG
LIPS -LIFMG /</description>
        <label>Order Quantity</label>
        <precision>15</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SapMaterialNumber__c</fullName>
        <description>Open Item / VBAP-MATNR
Return Item / VBAP-MATNR
Delivery Item / LIPS -MATNR / Optional  technical field. Not shown in the UI</description>
        <formula>Material__r.MaterialNumber__c</formula>
        <label>SAP Material Number</label>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/DeliveryComponentController.cls
public class DeliveryComponentController {
    public list<OrderItem__c> orderItems = null;
    public Delivery__c delivery { get; set; }

    
    public list<OrderItem__c> getOrderItems() {
        if (orderItems == null) {
            orderItems = [Select Id, Name, Material__c, SapMaterialNumber__c, OrderQuantity__c, ItemType__c from OrderItem__c where Delivery__c =:delivery.Id]; 
        }     
        return orderItems ;
    }    
        
    public DeliveryComponentController() {
    }
}