retrieveUnpackaged/objects/Delivery__c.object
<CustomObject>
    <fields>
        <fullName>DeliveryType__c</fullName>
        <description>/ The type of this delivery (out, in)</description>
        <label>Delivery Type</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoodsIssueDate__c</fullName>
        <description>Delivery / LIKP-WADAT_IST /</description>
        <label>Goods Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>/</description>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Deliveries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <label>Delivery Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Material__c.object
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Model Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>Delivery__c</fullName>
        <description>/</description>
        <label>Delivery Number</label>
        <referenceTo>Delivery__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ItemType__c</fullName>
        <description>/ in, out or cons.</description>
        <label>Item Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <description>/</description>
        <label>Model Number</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderQuantity__c</fullName>
        <description>VBAP-KWMENG
LIPS -LIFMG /</description>
        <label>Order Quantity</label>
        <precision>15</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>/</description>
        <label>Order Number</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SapMaterialNumber__c</fullName>
        <description>Open Item / VBAP-MATNR
Return Item / VBAP-MATNR
Delivery Item / LIPS -MATNR / Optional  technical field. Not shown in the UI</description>
        <formula>Material__r.MaterialNumber__c</formula>
        <label>SAP Material Number</label>
        <type>Text</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/OrderDetailController.cls
public with sharing class OrderDetailController {
    public Order__c order { get; set; }    
    public list<Delivery__c> deliveries { get; set; }
    public list<Delivery__c> returnDeliveries { get; set; }

    public list<OrderItem__c> orderItems { get; set; }
    public String[] orderItemFieldList { get; set; }
    public list<OrderItem__c> returnOrderItems { get; set; }
    public String[] returnOrderItemFieldList { get; set; } 

    public String[] deliveryItemFieldList { get; set; }
    public String[] returnDeliveryItemFieldList { get; set; }
    
    public OrderDetailController(ApexPages.StandardController controller) {
        this.order = (Order__c)controller.getRecord();
        
        orderItems = [Select Id, Name, Material__c, SapMaterialNumber__c, OrderQuantity__c, ItemType__c from OrderItem__c where Delivery__c = null and ItemType__c = 'out'];
        orderItemFieldList = new String[]{
            'ItemType__c','Item Type',
            'Material__c','Model No',
            'OrderQuantity__c','Quantity'
            };
            
        returnOrderItems = [Select Id, Name, Material__c, SapMaterialNumber__c, OrderQuantity__c, ItemType__c from OrderItem__c where Delivery__c = null and ItemType__c = 'in'];
        returnOrderItemFieldList = new String[]{
            'ItemType__c','Item Type',
            'Material__c','Model No',
            'OrderQuantity__c','Quantity',
            'ItemType__c','ItemType__c'};
            
            
//        deliveries = [Select Id, Name, GoodsIssueDate__c from Delivery__c where Order__c =:this.order.Id and DeliveryType__c = 'out'];
        deliveries = [Select Id, Name, GoodsIssueDate__c from Delivery__c where Order__c =:this.order.Id];
            
        deliveryItemFieldList = new String[]{
            'ItemType__c','Item Type',
            'Material__c','Model No',
            'OrderQuantity__c','Quantity'
            };

        returnDeliveries = [Select Id, Name, GoodsIssueDate__c from Delivery__c where Order__c =:this.order.Id and DeliveryType__c = 'in'];

        returnDeliveryItemFieldList = new String[]{
            'ItemType__c','Item Type',
            'Material__c','Model No',
            'OrderQuantity__c','Quantity'};
    }
}