retrieveUnpackaged/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Logs</relationshipLabel>
        <relationshipName>Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <description>DateOfBirth /</description>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City /</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country / ISO 3166 Country Code</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email /</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>FirstGivenName /</description>
        <label>First Given Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Gender /</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HomePhone__c</fullName>
        <description>HomePhone /</description>
        <label>Home Phone</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InsuranceName__c</fullName>
        <description>InsuranceName /</description>
        <label>Insurance Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language / ISO 639 Language code</description>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>LastName /</description>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaidenName__c</fullName>
        <description>MaidenName /</description>
        <label>Maiden Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MiddleName__c</fullName>
        <description>MiddleName /</description>
        <label>Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MobilePhone__c</fullName>
        <description>MobilePhone /</description>
        <label>Mobile Phone</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfficePhone__c</fullName>
        <description>OfficePhone /</description>
        <label>Office Phone</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PatientId__c</fullName>
        <description>ExternalPatientId /</description>
        <displayFormat>P{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Patient Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>PatientInsuranceId__c</fullName>
        <description>PatientInsuranceId /</description>
        <label>Patient Insurance ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <description>PostalCode /</description>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State /</description>
        <label>State / Prov</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street &amp; StreetNumber /</description>
        <label>Street / Nr</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/PatientController.cls
public with sharing class PatientController {
    public boolean access { get; set; }
    public String[] publicFields { get; set; }
    public String[] privateFields { get; set; }

    public PatientController(ApexPages.StandardController controller) {
/*        String publicFieldsString = 'PatientId__c';
        String privateFieldsString = 'Name,FirstName__c,MiddleName__c,LastName__c,MaidenName__c,Gender__c,Birthdate__c,Deceased__c,DateOfDecease__c,Street__c,PostalCode__c,City__c,State__c,Country__c,HomePhone__c,OfficePhone__c,MobilePhone__c,Email__c,Language__c,InsuranceName__c,PatientInsuranceId__c';        
    
        privateFields = privateFieldsString.split(',',0);
        publicFields = publicFieldsString.split(',',0);
        
        controller.addFields(privateFields);
        controller.addFields(publicFields);
        

        Set<String> fieldSet = new Set<String>();
        fieldSet.addAll(privateFields);
        fieldSet.addAll(publicFields);
        
        if (controller.getId() == null) {
//New Record        
            access = true;
        }
        else if (ApexPages.currentPage().getParameters().get('inline') == null  ) {
//Edit Modus        
//            access = true;
//            logAccess();
*/
//        }

/*
        if (qid == null) {
            patientObj = new Patient__c();
            access = true;
        } else {
        
            String query = 'Select ';
            for (String field : fieldSet) {
                query = query + field + ', ';
            }        
            query = query.substring(0,query.length() - 2) +  ' from Patient__c where Id = \'' + qid + '\'';
//            patientObj = Database.query('select Name, Id, ExplantDate__c from Patient__c where Id = \'' + qid + '\'');
            patientObj = Database.query(query);
        }
*/        
    }
    public PageReference access() {
//        writeLog(patient.Id, Datetime.now(), UserInfo.getUserId());
        logAccess();
        access = true;
        return null;
    }
    public PageReference logAccess() {
        String qid = ApexPages.currentPage().getParameters().get('id');
        if (qid != null) {
            Log__c log = new Log__c(Patient__c = qid);
            insert log;
        }
        return null;
    }
}