retrieveUnpackaged/objects/Patient__c.object
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/SystemId__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>SystemId</label>
</CustomObject>

retrieveUnpackaged/classes/TESTPatient_beforeInsert.cls
@isTest
private class TESTPatient_beforeInsert {
	static {
		//Make sure that TESTInit static constructor is executed before starting Tests
		TESTInit.init();    	
    }

    static testMethod void checkPatientHasPredefinedOwner() {
        Patient__c patient = [Select OwnerId FROM Patient__c Where Id = :TESTInit.patients.get(0).Id];
        System.assertEquals(patient.OwnerId,SystemId__c.getInstance('UserId_PatientOwner').Value__c);
    }
}